### ISSUE TITLE
Thanks for this great work / I used it in my tutorial

### ISSUE THREAD

**Issue by ksachdeva** [Shmuma/rethinking-2ed-julia#2]
Hi @Shmuma 

This is not really an issue rather FYI.

I recently made a tutorial on various PPLs using an example from Statistical Rethinking and have used the code snippet from your notebook. 

Here is the link to the tutorial:
https://www.youtube.com/watch?v=-C8PGgnF1yg

I have provided the link to your notebook in the description of the tutorial. The link is also shown on one of the screens in the video.

Again, thanks for the great work you have done here.

Regards
Kapil

**Comment by Shmuma** [comment]
Thanks a lot for letting me know and for the nice tutorial!
