### ISSUE TITLE
Pluto versions on StatisticalRethinkingJulia?

### ISSUE THREAD

**Issue by goedman** [Shmuma/rethinking-2ed-julia#3]
Hi Max (@Shmuma)

Slowly I'm getting back to taking a closer look on SR2 in Turing. As I said before, I really like what you are doing! And apparently so does Richard McElreath as he added a pointer to your work!

I started a couple of months ago to "translate" your Jupyter scripts to Pluto.jl. I now would like to update chapters 1-6 and add your chapters 7 to 9. Would you be ok with that? If so, I will drop my previous versions (which are still there). Of course Pluto.jl is different from Jupiter and single notebooks per chapter won't be practical in all cases, so for that reason they will be split up in a few Pluto notebooks (as I did for chapter 4).

Again, if you agree, I'm planning to rename the StatisticalRethinkingTuring.jl project to SR2TuringPluto.jl and add it to the overview page. We **could** do the same at some point with your repo `rethinking-2ed-julia`, e.g. rename it to `SR2TuringJupyter.jl` and move it over to the StatisticalRethinkingJulia GitHub organization. Completely up to you. In any case, I would at least point to the Jupyter notebooks at appropriate places.

On the Stan side I will go a similar route: StatisticalRethinkingStan.jl will be renamed to SR2StanPluto.jl. I don't think there will ever be a Jupyter version again, but that is ok.

In fact recently there have been some messages about old Jupyter notebook files left behind in StatisticalRethinking.jl. These were present way back in v1 and somehow they are still there and very large in some cases. Turns out it is only an issue if StatisticalRethinking.jl is `dev`-ed, the download takes pretty long, but otherwise it works fine and the files are not included in a package `add` operation. Julia's Pkg setup does not allow you to modify GitHub history so simply removing these files does not work.  If this becomes  a big issue, from the message exchange, I do know a remedy but I'm holding off doing that right now. 

Best, Rob

**Comment by Shmuma** [comment]
Hi Rob!

I'm totally in favour of your idea! If you need any help from my side - just drop me a note. Meanwhile, going to finalize book chapters, as it took longer than I expected initially :)

With best regards, Max

**Comment by goedman** [comment]
Hi Max (@Shmuma),

I'll do SR2TuringPluto.jl first as a test case. Should be done later this week. Then I'll do SR2StanPluto.jl And finally we can move rethinking-2ed-julia over and rename it to SR2TuringJupyter.jl. I think only you can do the move (I don't have access to your repo and you have access to both).

Best, Rob

**Comment by Shmuma** [comment]
Ok, sounds like a plan. 

In terms of repo, I think it will be easier to fork it and then rename.
