### ISSUE TITLE
 rethinking-2ed-julia/13-Chapter 13. Models with Memory.ipynb typo

### ISSUE THREAD

**Issue by PeetoomHeida** [Shmuma/rethinking-2ed-julia#4]
In the model specifications for Code 13.2 and Code 13.3 in the file mentioned in the title, I think that the code ```tank_size = length(levels(d.tank))``` should be changed to ```tank_size = length(levels(tank))```. As it stands currently, though the ```tank``` argument is passed into the model function as ```d.tank``` (line 116 of the file), the function doesn't actually make any reference to the ```tank``` variable, but rather uses ```d.tank``` directly, no matter what is passed in as the ```tank``` argument.

This change should apply to the code on lines 109 and 136.

**Comment by Shmuma** [comment]
Good point, thanks! Will fix
